title: Josu Alonso
email: josu93alonso@gmail.com
description: >-
  I am a Data Scientist & Data Analyst applying statistics and programming to bring value to organizations.
  I aim to make the journey through machine learning concepts easy by using illustrations, code and mathematical explanations.
twitter_username: josumsc
github_username: josumsc
search: true

minimal_mistakes_skin: contrast
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

author:
  name   : "Josu Alonso"
  avatar : "/images/bio-photo.jpeg"
  bio    : "Data Scientist & Analyst"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/josumsc"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/josumsc"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/josu-alonso-castanedo/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/josumsc"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/josumsc"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  